import { Form } from 'components'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next, Tailwind, Storybook - Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <div className="flex h-screen flex-col items-center justify-center">
            <Form />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
